<?php
/**
 * @package    Leytech_ColorAttribute
 * @author     Chris Nolan (chris@leytech.co.uk)
 * @copyright  Copyright (c) 2017 Leytech
 * @license    https://opensource.org/licenses/MIT  The MIT License  (MIT)
 */

if (!$this->helper('leytech_colorattribute')->isEnabled()) {
    return;
}
?>

<?php $colorPicker = $this->helper('leytech_colorattribute')->getColorPicker(); ?>

<?php if ($colorPicker == 'spectrum') : ?>
    <script type="text/javascript">
        jQuery( document ).ready(function( $ ) {
            $("input.spectrum").spectrum({
                <?php echo $this->helper('leytech_colorattribute')->getSpectrumOptions(); ?>
            });
        });
    </script>
<?php endif; ?>