<?php
if (!$this->helper('leytech_colorattribute')->isEnabled()) {
    return;
}
?>

<?php $colorPicker = $this->helper('leytech_colorattribute')->getColorPicker(); ?>
<?php $includeJquery = $this->helper('leytech_colorattribute')->getIncludeJquery(); ?>

<?php if ($colorPicker == 'jscolor') : ?>
    <script type="text/javascript" src="/js/leytech/colorattribute/jscolor/jscolor.min.js"></script>
<?php endif; ?>

<?php if ($colorPicker == 'color-picker') : ?>
    <link rel="stylesheet" type="text/css" href="/js/leytech/colorattribute/color-picker/color-picker.min.css" />
    <script type="text/javascript" src="/js/leytech/colorattribute/color-picker/color-picker.min.js"></script>
    <script type="text/javascript">
        var picker = new CP(document.querySelector('input.color-attribute'));
        picker.on("change", function(color) {
            this.target.value = '#' + color;
        });
    </script>
<?php endif; ?>

<?php if ($colorPicker == 'spectrum' && $includeJquery) : ?>
    <script type="text/javascript" src="/js/leytech/colorattribute/jquery/jquery-3.2.1.min.js"></script>
    <script type="text/javascript" src="/js/leytech/colorattribute/jquery/noConflict.js"></script>
<?php endif; ?>

<?php if ($colorPicker == 'spectrum') : ?>
    <link rel="stylesheet" type="text/css" href="/js/leytech/colorattribute/spectrum/spectrum.css" />
    <script type="text/javascript" src="/js/leytech/colorattribute/spectrum/spectrum.js"></script>
    <script type="text/javascript">
        jQuery( document ).ready(function( $ ) {
            $("input.color-attribute").spectrum({
                showAlpha: true,
                preferredFormat: "hex",
                showInput: true
            });
        });
    </script>
<?php endif; ?>
